// AppIcons — the single source of mdit's application / window icon.
//
// The mark mirrors the Pengy icon (~/Personal/Pengy/pengy.png): a **solid white
// disc with a transparent outside** (same radius ratio, 0.4872 * size, verified
// against the source PNG), carrying mdit's own glyph instead of the penguin — a
// bold **`#`**, the markdown ATX heading element, in the mascot's near-black.
//
// The PNGs live in assets/icons/ (generated by tools/make_icon.py, one natively
// rendered file per size) and are compiled into the binary through
// resources/mdit.qrc, so `:/icons/mdit-<size>.png` is always available and the
// app needs no external files at runtime.
#pragma once

#include <QIcon>
#include <QString>

namespace AppIcons
{
// All sizes compiled into the resource as one QIcon, so Qt picks the right one
// for the context (16 px in a taskbar/title bar, 256/512 in a launcher).
QIcon windowIcon();

// The resource path of the icon rendered at `size`
// (e.g. ":/icons/mdit-32.png"). Sizes: 16, 24, 32, 48, 64, 128, 256, 512.
QString iconPath(int size);
} // namespace AppIcons
